const ar = {
  temperature: "درجة الحرارة الداخلية",
  humidity: "الرطوبة الداخلية",
  connected: "متصل",
  disconnected: "غير متصل",
  liveData: "البيانات المباشلر",
  preferences: "الإعدادات",
  light: "فاتح",
  dark: "داكن",
  weatherStation: "بيانات الطقس",
  windAngle: "زاوية الرياح",
  aerostatPosition: "موقع واتجاه المنطاد",
  longitude: "خط العرض",
  latitude: "سرعة الرياح",
  altitude: "الارتفاع",
  roll: "الميلان الجانبي",
  pitch: "الميلان الطولي",
  heading: "",
  windSpeed: "سرعة الرياح",
  airTemp: "درجة الحرارة الخارجية:",
  baroPress: "الضغط الجوي:",
  pressures: "قراءات الضغط",
  hullPressure: "ضغط الهليوم",
  curtainHeight: "ارتفاع ستارة البالونيت",
  ballonetAir: "ضغط البالونيت",
  liftForce: "قراءات التوتر",
  maxTension: "أقصى توتر",
  currentTension: "التوتر الحالي",
  select: "اختيار نقاط البيانات ⏷",
  lineChart: "تصور البيانات",
  hullHelium: "ضغط الهليوم",
  barometricPressure: "الضغط الجوي",
  outsideTemperature: "درجة الحرارة الخارجية",
  ballonetPressure: "ضغط البالونيت",
  ballonetCurtain: "ارتفاع ستارة البالونيت",
  phase2: "Phase 2",
  dataLogging: "تخزين البيانات",
  logFile: "ملف السجل",
  browse: "اختيار ملف",
  config: " ",
  relayControls: "إعدادات المرحلات",
};
export default ar;
