const en = {
  temperature: "Temperature:",
  humidity: "Humidity:",
  connected: "Connected",
  disconnected: "Disconnected",
  liveData: "Live Data:",
  preferences: "Preferences",
  light: "Light",
  dark: "Dark",
  weatherStation: "Weather Station",
  windAngle: "Wind Angle",
  aerostatPosition: "Aerostat Position and Orientation",
  longitude: "Longitude",
  latitude: "Latitude",
  altitude: "Altitude",
  roll: "Roll",
  pitch: "Pitch",
  heading: "Heading",
  windSpeed: "Wind Speed",
  airTemp: "Air Temp:",
  baroPress: "Baro Press:",
  pressures: "Pressure Readings",
  hullPressure: "Hull Pressure",
  curtainHeight: "Curtain Height",
  ballonetAir: "Ballonet Air",
  lift: "Lift",
  maxTension: "Max Tension",
  currentTension: "Current Tension",
  select: "Select Data Points ⏷",
  lineChart: "Line Chart",
  hullHelium: "Hull Helium",
  barometricPressure: "Barometric Pressure",
  outsideTemperature: "Outside Temperature",
  ballonetPressure: "Ballonet Pressure",
  ballonetCurtain: "Ballonet Curtain",
  phase2: "Phase 2",
  dataLogging: "Data Logging",
  logFile: "Log File",
  browse: "Browse",
  config: "Config",
  relayControls: "Relay Controls",
};
export default en;
