name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Frontend: Set up Node.js and install dependencies from aerostat_webapp
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies for Frontend
        run: |
          cd aerostat_webapp
          npm install

      - name: Build Frontend (Vite)
        run: |
          cd aerostat_webapp
          npm run build

      - name: Compress Frontend Source Code
        run: |
          zip -r frontend-source-code.zip aerostat_webapp/

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.sha }}
          release_name: Release v${{ github.sha }}
          assets:
            - frontend-source-code.zip
